/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.psc.sgpl.apresentacao;

import br.edu.ifnmg.psc.sgpl.aplicacao.Fornecedor;
import br.edu.ifnmg.psc.sgpl.aplicacao.ItemPregao;
import br.edu.ifnmg.psc.sgpl.aplicacao.Pedido;
import br.edu.ifnmg.psc.sgpl.aplicacao.Produto;
import br.edu.ifnmg.psc.sgpl.aplicacao.Repositorio;
import br.edu.ifnmg.psc.sgpl.aplicacao.StatusItem;
import br.edu.ifnmg.psc.sgpl.aplicacao.StatusPregao;
import br.edu.ifnmg.psc.sgpl.aplicacao.StatusPregaoItem;
import br.edu.ifnmg.psc.sgpl.persistencia.ItemPregaoDao;
import br.edu.ifnmg.psc.sgpl.persistencia.ProdutoDao;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ewertoncardoso
 */
public class StatusItemPregao extends javax.swing.JInternalFrame {

    
    private ItemPregao itemPregao = null;
    
    private ItemPregaoDao itemPregaoDao = null;
    
    
    /**
     * Creates new form StatusItemPregao
     */
    public StatusItemPregao(int idItem) {
        
        initComponents();
        try {
            this.itemPregaoDao = new ItemPregaoDao();
            
            this.itemPregao = itemPregaoDao.Abrir(idItem);
            
            lblPrduto.setText(this.itemPregao.getProduto().toString());
            lblQtd.setText(Double.toString(this.itemPregao.getQuantidade()));
 
            if(this.itemPregao.getStatusItem() != null)
                lblStatus.setText(this.itemPregao.getStatusItem().getDescricao());
            else
                lblStatus.setText("-");
            
            if(this.itemPregao.getForncedor() != null)
                lblFornecedor.setText(this.itemPregao.getForncedor().getNomeFantasia());
            else
                lblFornecedor.setText("-");
            
            ComboBoxModel model = new DefaultComboBoxModel(StatusPregaoItem.values());
            selStatusItem.setModel(model);
            
            Repositorio<Fornecedor> repositorioFornecedor = Repositorios.getFornecedorRepositorio();

            List<Fornecedor> fornecedores = repositorioFornecedor.Buscar(null);
            

            ComboBoxModel modelFornecedor = new DefaultComboBoxModel(fornecedores.toArray());
            
            selFornecedor.setModel(modelFornecedor);
            selFornecedor.insertItemAt("", 0);
            selFornecedor.setSelectedIndex(0);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StatusItemPregao.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(StatusItemPregao.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPrduto = new javax.swing.JLabel();
        selStatusItem = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblQtd = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblFornecedor = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        selFornecedor = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("SGPL - Atualizar status e Fornecedor");

        jLabel1.setText("Produto:");

        jLabel2.setText("Quantidade:");

        jLabel3.setText("Alterar para:");

        lblPrduto.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblQtd.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N

        jLabel4.setText("Status atual:");

        lblStatus.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N

        jLabel5.setText("Fornecedor vendedor:");

        lblFornecedor.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N

        jLabel6.setText("Fornecedor:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar))
                    .addComponent(lblPrduto)
                    .addComponent(selStatusItem, 0, 266, Short.MAX_VALUE)
                    .addComponent(lblQtd)
                    .addComponent(lblStatus)
                    .addComponent(lblFornecedor)
                    .addComponent(selFornecedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblPrduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblQtd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblFornecedor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(selStatusItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(selFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        this.itemPregao.setStatusItem((StatusPregaoItem) selStatusItem.getSelectedItem());
        
        if(selFornecedor.getSelectedIndex() > 0) 
            this.itemPregao.setForncedor((Fornecedor) selFornecedor.getSelectedItem());
        
        try{
            this.itemPregaoDao.Salvar(this.itemPregao);
            JOptionPane.showMessageDialog(rootPane, "Registro salvo com sucesso!");
            this.setVisible(false);
            this.dispose();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao salvar!");
        }

        
        
    }//GEN-LAST:event_btnSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblFornecedor;
    private javax.swing.JLabel lblPrduto;
    private javax.swing.JLabel lblQtd;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JComboBox<String> selFornecedor;
    private javax.swing.JComboBox<String> selStatusItem;
    // End of variables declaration//GEN-END:variables
}
